// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT0qwkusDfxEYE_OrbQwq_Ylb_eHhZoxc',
    appId: '1:212274995241:web:afc5dd57459a3349253c38',
    messagingSenderId: '212274995241',
    projectId: 'blnk-4fe18',
    authDomain: 'blnk-4fe18.firebaseapp.com',
    storageBucket: 'blnk-4fe18.appspot.com',
    measurementId: 'G-ELYQSBWVLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWDgDZxdELbqsB3CzUMt4sGPRgATUJu8',
    appId: '1:212274995241:android:4c54b340839657bc253c38',
    messagingSenderId: '212274995241',
    projectId: 'blnk-4fe18',
    storageBucket: 'blnk-4fe18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOXMSi1afDw0q5RlwiCp3H1J-BtXIZVg',
    appId: '1:212274995241:ios:d2724872de4c1598253c38',
    messagingSenderId: '212274995241',
    projectId: 'blnk-4fe18',
    storageBucket: 'blnk-4fe18.appspot.com',
    iosBundleId: 'com.example.blnkMobileTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOXMSi1afDw0q5RlwiCp3H1J-BtXIZVg',
    appId: '1:212274995241:ios:d2724872de4c1598253c38',
    messagingSenderId: '212274995241',
    projectId: 'blnk-4fe18',
    storageBucket: 'blnk-4fe18.appspot.com',
    iosBundleId: 'com.example.blnkMobileTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT0qwkusDfxEYE_OrbQwq_Ylb_eHhZoxc',
    appId: '1:212274995241:web:497283e63513f04a253c38',
    messagingSenderId: '212274995241',
    projectId: 'blnk-4fe18',
    authDomain: 'blnk-4fe18.firebaseapp.com',
    storageBucket: 'blnk-4fe18.appspot.com',
    measurementId: 'G-7GHVDR2HW3',
  );
}
